### ISSUE TITLE
Question: is it possible to run the docker image without the echo server?

### ISSUE THREAD

**Issue by dezoitodemaio** [webhooksite/webhook.site#165]
I'm trying this compose config

```
services:
  webhook:
    image: "webhooksite/webhook.site"
    command: php artisan queue:work --daemon --tries=3 --timeout=10
    ports:
      - "8084:80"
    environment:
      - APP_URL=http://localhost:8084
      - APP_LOG=errorlog
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=array
      - SESSION_DRIVE=array
      - QUEUE_DRIVER=sync`
```

but i get this error

```
webhook-1  | 2024/08/05 21:47:06 [emerg] 211#211: host not found in upstream "laravel-echo-server" in /etc/nginx/conf.d/nginx.conf:27
webhook-1  | nginx: [emerg] host not found in upstream "laravel-echo-server" in /etc/nginx/conf.d/nginx.conf:27

```
